spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.30.67.154:3306/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.67.154:3333


server:
  port: 20035


ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000