spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.22.76:3333
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**,/test
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_route
          uri: lb://mall-thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mall_route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: mall_auth_route
          uri: lb://mall-auth
          predicates:
            - Host=auth.mall.com

        - id: mall_auth_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com

        - id: mall_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.mall.com





  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.24.22.76:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 88




