spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.25.95.135:3333
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: admin_route
          uri: lb://renren_fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren_fast/$\{segment}
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 88




